server:
  port: 8086

spring:
  application:
    name: api-gateway001

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ruta-usuarios
              uri: http://localhost:8081
              predicates:
                - Path=/api/usuarios/**
              filters:
                - StripPrefix=1

            - id: ruta-metas
              uri: http://localhost:8083/metas
              predicates:
                - Path=/api/metas/**
              filters:
                - StripPrefix=1

            - id: ruta-notas
              uri: http://localhost:8083/notas
              predicates:
                - Path=/api/notas/**
              filters:
                - StripPrefix=1

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URL:http://eureka-server:8761/eureka}